# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1.0.1
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-cookies dash[dev,testing]
#        pip install pytest pytest-cov pytest-cookies selenium==4.1.0 pytest-selenium==2.0.1 dash[dev,testing] webdriver-manager==3.5.2 selenium-wire==4.5.6
    - name: Test with pytest
      run: |
        pytest --cov=dash_extensions --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov-report=xml tests
#    - name: Upload pytest test results
#      uses: actions/upload-artifact@v2
#      with:
#        name: pytest-results-${{ matrix.python-version }}
#        path: junit/test-results-${{ matrix.python-version }}.xml
#        # Use always() to always run this step to publish test results when there are test failures
#      if: ${{ always() }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1